import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormArray, FormBuilder, FormControl, Validators } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';

import { T1Service } from '../t-1.service';
import { IT1 } from '../it-1';
import { BaseDetailsComponent, Globals, PickerDialogService, ErrorService, FieldType } from 'src/app/common/shared';

@Component({
  selector: 'app-t-1-details',
  templateUrl: './t-1-details.component.html',
  styleUrls: ['./t-1-details.component.scss'],
})
export class T1DetailsComponent extends BaseDetailsComponent<IT1> implements OnInit {
  title = 'T1';
  parentUrl = 't1';
  constructor(
    public formBuilder: FormBuilder,
    public router: Router,
    public route: ActivatedRoute,
    public dialog: MatDialog,
    public global: Globals,
    public t1Service: T1Service,
    public pickerDialogService: PickerDialogService,
    public errorService: ErrorService
  ) {
    super(formBuilder, router, route, dialog, global, pickerDialogService, t1Service, errorService);
  }

  ngOnInit() {
    this.entityName = 'T1';
    this.setAssociations();
    super.ngOnInit();
    this.setForm();
    this.getItem();
  }

  setForm() {
    this.itemForm = this.formBuilder.group({
      id: [{ value: '', disabled: true }, Validators.required],
      str: [],
      ca: [],
      file: [],
      fileSource: [],
      fpa: new FormArray([]),
      flpa: new FormArray([]),
    });

    this.fields = [
      {
        name: 'ca',
        label: 'ca',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.String,
      },

      {
        name: 'file',
        label: 'file',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.File,
      },

      {
        name: 'flpa',
        label: 'flpa',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.FloatingPointArray,
      },

      {
        name: 'fpa',
        label: 'fpa',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.FixedPointArray,
      },

      {
        name: 'str',
        label: 'str',
        isRequired: false,
        isAutoGenerated: false,
        type: FieldType.String,
      },
    ];
  }

  onItemFetched(item: IT1) {
    this.item = item;
    this.item.fpa.forEach(elem => {
      (<FormArray>this.itemForm.get('fpa')).push(new FormControl(elem));
    });
    delete item.flpa;
    delete item.fpa;
    delete item.file;
    this.itemForm.patchValue(item);
  }

  setAssociations() {
    this.associations = [];

    this.childAssociations = this.associations.filter((association) => {
      return association.isParent;
    });

    this.parentAssociations = this.associations.filter((association) => {
      return !association.isParent;
    });
  }

  onSubmit() {
    let t1 = this.itemForm.getRawValue();
    const formData = new FormData();
    formData.append('file', this.itemForm.get('fileSource').value);
    formData.append('id', this.itemForm.get('id').value);
    formData.append('str', this.itemForm.get('str').value);
    formData.append('ca', this.itemForm.get('ca').value);
    formData.append('fpa', this.itemForm.get('fpa').value);
    super.onSubmit(formData);
  }

  // onSubmit(){
  //   const formData = new FormData();
  //   formData.append('file', this.itemForm.get('fileSource').value);
  //   formData.append('id', this.itemForm.get('id').value);
  //   formData.append('str', this.itemForm.get('str').value);
  //   formData.append('ca', this.itemForm.get('ca').value);
  //   formData.append('fpa', this.itemForm.get('fpa').value);
   
  //   this.dataService.update(<any>formData, this.idParam)
  //     .subscribe(res => {
  //     })
  // }
}
